/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DefaultPage: typeof import('./src/components/main/page/DefaultPage.vue')['default']
    HeaderRender: typeof import('./src/components/header/HeaderRender.vue')['default']
    HeaderTab: typeof import('./src/components/header/HeaderTab.vue')['default']
    IconAdd: typeof import('./src/components/icons/IconAdd.vue')['default']
    IconAudioMuted: typeof import('./src/components/icons/IconAudioMuted.vue')['default']
    IconAudioOn: typeof import('./src/components/icons/IconAudioOn.vue')['default']
    IconBack: typeof import('./src/components/icons/IconBack.vue')['default']
    IconReload: typeof import('./src/components/icons/IconReload.vue')['default']
    IconSpinner: typeof import('./src/components/icons/IconSpinner.vue')['default']
    IconTabClose: typeof import('./src/components/icons/IconTabClose.vue')['default']
    LoadPage: typeof import('./src/components/main/page/LoadPage.vue')['default']
    RenderWebView: typeof import('./src/components/main/page/RenderWebView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
