/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DefaultPage: typeof import('./src/components/main/page/DefaultPage.vue')['default']
    HeaderDownloads: typeof import('./src/components/header/HeaderDownloads.vue')['default']
    HeaderDownloadsExtIcon: typeof import('./src/components/header/HeaderDownloadsExtIcon.vue')['default']
    HeaderFavoriteBar: typeof import('./src/components/header/HeaderFavoriteBar.vue')['default']
    HeaderMenu: typeof import('./src/components/header/HeaderMenu.vue')['default']
    HeaderProfile: typeof import('./src/components/header/HeaderProfile.vue')['default']
    HeaderRender: typeof import('./src/components/header/HeaderRender.vue')['default']
    HeaderSuggest: typeof import('./src/components/header/HeaderSuggest.vue')['default']
    HeaderTab: typeof import('./src/components/header/HeaderTab.vue')['default']
    IconAdd: typeof import('./src/components/icons/IconAdd.vue')['default']
    IconAudioMuted: typeof import('./src/components/icons/IconAudioMuted.vue')['default']
    IconAudioOn: typeof import('./src/components/icons/IconAudioOn.vue')['default']
    IconBack: typeof import('./src/components/icons/IconBack.vue')['default']
    IconDirectory: typeof import('./src/components/icons/IconDirectory.vue')['default']
    IconDownloadDefault: typeof import('./src/components/icons/IconDownloadDefault.vue')['default']
    IconDownloadDOCX: typeof import('./src/components/icons/IconDownloadDOCX.vue')['default']
    IconDownloadEXE: typeof import('./src/components/icons/IconDownloadEXE.vue')['default']
    IconDownloadPDF: typeof import('./src/components/icons/IconDownloadPDF.vue')['default']
    IconDownloadTXT: typeof import('./src/components/icons/IconDownloadTXT.vue')['default']
    IconFavoriteOff: typeof import('./src/components/icons/IconFavoriteOff.vue')['default']
    IconFavoriteOn: typeof import('./src/components/icons/IconFavoriteOn.vue')['default']
    IconMenu: typeof import('./src/components/icons/IconMenu.vue')['default']
    IconMenuConfiguration: typeof import('./src/components/icons/IconMenuConfiguration.vue')['default']
    IconMenuDefines: typeof import('./src/components/icons/IconMenuDefines.vue')['default']
    IconMenuHistoric: typeof import('./src/components/icons/IconMenuHistoric.vue')['default']
    IconPause: typeof import('./src/components/icons/IconPause.vue')['default']
    IconProfile: typeof import('./src/components/icons/IconProfile.vue')['default']
    IconProfileDownload: typeof import('./src/components/icons/IconProfileDownload.vue')['default']
    IconProfileMin: typeof import('./src/components/icons/IconProfileMin.vue')['default']
    IconReload: typeof import('./src/components/icons/IconReload.vue')['default']
    IconResume: typeof import('./src/components/icons/IconResume.vue')['default']
    IconSpinner: typeof import('./src/components/icons/IconSpinner.vue')['default']
    IconTabClose: typeof import('./src/components/icons/IconTabClose.vue')['default']
    IconViewTab: typeof import('./src/components/icons/IconViewTab.vue')['default']
    IconWindowClose: typeof import('./src/components/icons/IconWindowClose.vue')['default']
    IconWindowMaximize: typeof import('./src/components/icons/IconWindowMaximize.vue')['default']
    IconWindowMinimize: typeof import('./src/components/icons/IconWindowMinimize.vue')['default']
    IconWindowUnmaximize: typeof import('./src/components/icons/IconWindowUnmaximize.vue')['default']
    MaterialButton: typeof import('./src/components/material/MaterialButton.vue')['default']
    MaterialInputText: typeof import('./src/components/material/MaterialInputText.vue')['default']
    MaterialList: typeof import('./src/components/material/MaterialList.vue')['default']
    RenderWebView: typeof import('./src/components/main/page/RenderWebView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
